Data updates.

diff --git a/data/bash_aliases b/data/bash_aliases
--- a/data/bash_aliases
+++ b/data/bash_aliases
@@ -1,5 +1,54 @@
+# My bask aliases - Ivan Llanas
+
 #export LC_ALL="C" # Breaks unicode characters!
 export LS_COLORS=""
+
+# Aliases support functions --------------------------------------------
+function ___cmd_descr ()
+{
+   local b1='\e[1m'
+   local b0='\e[0m'
+
+   echo -e " "$b1$1$b0" - "$2$b0
+}
+
+function ___cmd_usage ()
+{
+   local bg1='\e[47m'
+   local b1='\e[0;30m'
+   local b0='\e[0m'
+
+   echo -e " Usage: "$b1$bg1 $1 $b0
+}
+
+function ___cmd_error ()
+{
+   local b1='\e[37m'
+   local b2='\e[1;33m'
+   local b0='\e[0m'
+   local bg='\e[41m'
+
+   echo -e -n $bg$b1" Error: "$b2$1$b0
+   echo -e    $bg$b1" - "$2" "$b0
+}
+
+function ___trim ()
+{
+   local s=$1
+
+   # Turn on the extglob shell option
+   shopt -s extglob
+   ## Trim leading whitespaces
+   s="${s##*( )}"
+   ## Trim trailing whitespaces
+   s="${s%%*( )}"
+   # 5. Print final result
+   echo $s
+   # Turn off the extglob shell option
+   shopt -u extglob
+}
+
+# ----------------------------------------------------------------------
 
 # Common aliases
 alias ..="cd .."
@@ -24,22 +73,39 @@ alias dg="d --git"
    dg_description="Directory listing, full information, git status."
 alias l="less"
    l_description="Less."
-alias q=geany
+alias q=_q
    q_description="Preferred text editor (geany)."
+function _q()
+{
+   # We don't want to see geany's console messages anytime...
+   geany "$@" > /dev/null &
+}
 alias sq="sudo nano"
    sq_description="sudo nano."
 alias ea="q ~/.bash_aliases"
    ea_description="Edit aliases."
 alias ra="unalias -a && source ~/.bash_aliases"
    ra_description="Re-read aliases."
-alias hg="history|grep"
-   hg_description="Find in history."
+alias fh="__fh"
+   fh_description="Find in history."
+function __fh ()
+{
+   if [ $# -lt 1 ]; then
+      ___cmd_descr "fh" "$fh_description"
+      ___cmd_usage "fh text"
+   else
+      history|grep $1
+   fi
+}
+
+# Saved from original .bashrc
 alias grep="grep --color=auto"
    grep_description="grep using colors."
 alias egrep="egrep --color=auto"
    egrep_description="egrep using colors."
 alias fgrep="fgrep --color=auto"
    fgrep_description="fgrep using colors."
+
 
 alias start="xdg-open"
    start_description="Launch file with the default application."
@@ -71,6 +137,25 @@ alias logout=gnome-session-quit
 alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
    alert_description="Add an alert to Gnome alerts (calendar button)."
 
+alias fn="realpath \$1"
+   fn_description="Print the full path of a given file/directory."
+
+alias fp="__fp"
+   fp_description="Find pid of a given process name."
+function __fp ()
+{
+   if [ $# -lt 1 ]; then
+      ___cmd_descr "fp" "$fp_description"
+      ___cmd_usage "fp name/fragment"
+   else
+      pgrep -ia $1
+   fi
+}
+
+# Git --------------------------------------------------------
+alias cgtk="xclip -sel clip /home/ivan/.config/ivan/git-token.txt && echo Token copied to the clipboard."
+   cgtk_description="Copies the github security token to the clipboard."
+
 # Debian --------------------------------------------------------
 function DebianAliases ()
 {
@@ -85,7 +170,7 @@ function DebianAliases ()
         *"Ubuntu"*) os_is_ubuntu=1;;
         *"Debian"*) os_is_debian=1;;
         *"mint"*)   os_is_ubuntu=1;;
-        *) echo "Unknow linux version";;
+        *) echo "DebianAliases: Unknown linux version.";;
       esac
    fi
    if [ $os_is_debian -gt 1 ]; then
@@ -102,7 +187,6 @@ alias car=cat
    car_description="cat correction."
 alias cay=cat
    cay_description=$car_description
-
 
 # INAS ----------------------------------------------------------
 alias smbed="sudo nano /etc/samba/smb.conf"
@@ -135,7 +219,7 @@ if test -f "$HOME/doom/ports/gzdoom/current/gzdoom"; then
       gzx_description="Launch GZDoom with \"portable\" settings file and XS wad(s)."
 fi
 
-# WoW servers ---------------------------------------------------
+# WoWSSS server -------------------------------------------------
 if test -f "$HOME/wowsss/wowsss/wowsss.sh"; then
    alias wow="$HOME/wowsss/start.sh"
       wow_description="Launch WoWSSS."
@@ -146,11 +230,11 @@ fr_description="Show memory and disk usage."
 if test -d "/shared/videoteca"; then
       alias fr="echo && free -h && echo &&  df -h / /shared/videoteca /shared/filter && echo"
 else
-   if test -d "$HOME/Dropbox"; then
-      alias fr="echo && free -h && echo &&  df -h / $HOME/Dropbox $HOME/VM && echo"
+   if [ $HOSTNAME = "cc" ]; then
+      alias fr="echo && free -h && echo &&  df -h / $HOME/Dropbox $HOME/VM $HOME/store && echo"
    else
       alias fr="echo && free -h && echo &&  df -h / && echo"
-   fi      
+   fi
 fi
 
 # Big aliases ---------------------------------------------------
@@ -160,8 +244,8 @@ alias ft=_ft
 function _ft ()
 {
    if [ $# -lt 1 ]; then
-      echo "ft - $ft_description"
-      echo "Usage: ft text [path=.]"
+      ___cmd_descr "ft" "$ft_description"
+      ___cmd_usage "ft text [path=.]"
    else
       local text=$1
       local path=$2
@@ -178,8 +262,8 @@ alias count=_count_files
 function _count_files ()
 {
    if [ $# -lt 1 ]; then
-      echo "count - $count_description"
-      echo "Usage: count [path=.]"
+      ___cmd_descr "count" "$count_description"
+      ___cmd_usage "count path=."
    else
       local path=$1
       local d=
@@ -202,8 +286,8 @@ alias chmn="chm 644"
 function _chm ()
 {
    if [ $# -lt 1 ]; then
-      echo "chm - $chm_description"
-      echo "Usage: chm value [path=.]"
+      ___cmd_descr "chm" "$chm_description"
+      ___cmd_usage "chm value [path=.]"
    else
       local value=$1
       local path=$2
@@ -220,9 +304,13 @@ alias go=_go_dir
    go_description="cd shortcuts by ID."
 _go_dirs=("gz    :~/doom/ports/gzdoom/current" \
           "wad   :~/doom/wads" \
+          "docs  :~/Dropbox/Documents" \
+          "save  :~/Dropbox/Apps/Games/_savegames/Active" \
+          "web   :~/Dropbox/Web" \
           "vm    :~/VM" \
           "dw    :~/Downloads" \
           "wow   :~/Scripts/wowssses" \
+          "ivan  :~/.config/ivan" \
           "eza   :~/.config/eza" \
           "geany :~/.config/geany" \
           "xnview:~/.config/xnviewmp" \
@@ -241,15 +329,15 @@ function _go_dir ()
    local c2="\e[0m"
 
    if [ $# -lt 1 ]; then
-      echo "go - $go_description"
-      echo "Usage: go dir-id"
+      ___cmd_descr "go" "$go_description"
+      ___cmd_usage "go dir-id"
       for (( i=0 ; i<$n ; i++ ));
       do
-         
+
          s=${_go_dirs[$i]}
          IFS=":"
             set $s
-            id=$(_trim $1)
+            id=$(___trim $1)
             dir=$2
 
             printf "       go "
@@ -265,31 +353,15 @@ function _go_dir ()
          s=${_go_dirs[$i]}
          IFS=":"
             set $s
-            id=$(_trim $1)
+            id=$(___trim $1)
             dir=$2
          if [ "$id" = "$id0" ]; then
             cd "${dir/\~/$HOME}"
             return
          fi
       done
-      echo Dir-id \<$id0\> not found.
+      ___cmd_error "go" "Dir-id <$id0> not found."
    fi
-}
-
-function _trim ()
-{
-   local s=$1
-
-   # Turn on the extglob shell option
-   shopt -s extglob
-   ## Trim leading whitespaces
-   s="${s##*( )}"
-   ## Trim trailing whitespaces
-   s="${s%%*( )}"
-   # 5. Print final result
-   echo $s
-   # Turn off the extglob shell option
-   shopt -u extglob
 }
 
 # ---------------------------------------------------------------
@@ -298,8 +370,8 @@ alias desktop_link=_desktop_link
 function _desktop_link ()
 {
    if [ $# -lt 2 ]; then
-      echo "?? - $_description"
-      echo "Usage: ?? source-file destination-link"
+      ___cmd_descr "??" "$??_description"
+      ___cmd_usage "?? source-file destination-link"
    else
       local source=$1
       local dest=$2
@@ -315,63 +387,98 @@ function _list_aliases ()
    local aliases=$(compgen -a)
    local desc=0
    local width2=
-   local count=
    local i=1
-   local value=
-   local varname=
-   local c1=
-   local c2=
+   local cmd=
+   local cr=0
 
    let width2=$COLUMNS-3
    let n=width2/16
 
    if [[ $1 != "" ]]; then
+      cmd=$1
+      local cmdv=${BASH_ALIASES[$cmd]}
+      if [ "$cmdv" = "" ]; then
+         ___cmd_error "all" "Unknown alias <$cmd>."
+      else
+         ___print_alias 1 0 $cmd
+         return
+      fi
       desc=1
    fi
 
-   printf "   "
-   while IFS= read -r line ; do
-      value=${BASH_ALIASES[$line]}
-      if [[ $value == *"sudo "* ]]; then
-         suf="*"
-         c1="\e[93m"
-         c2="\e[0m"
-      else
-         suf=""
-         c1=
-         c2=
-      fi
+   if [ $desc -eq 0 ]; then
+      printf "   "
+   fi
 
-      echo -e -n $c1
-      printf %-16s $line$suf
-      echo -e -n $c2
+   while IFS= read -r cmd ; do
 
-      if [ $desc -gt 0 ]; then
-         varname=${line//\./_}"_description"
-         if [[ -v $varname ]]; then
-            description=${!varname}
-         else
-            varname="_"$line"_description"
-            if [[ -v $varname ]]; then
-               description=${!varname}
-            else
-               description="?"
-            fi
-         fi
-         echo " - $description"
-         printf "   "
-      else
+      ___print_alias $desc 1 $cmd
 
+      cr=0
+      if [ $desc = 0 ]; then
          let i=i+1
-         if [ $i -gt $n ]; then
+         if [ $i -ge $n ]; then
             printf "\n   "
             i=1
+            cr=1
          fi
+       fi
 
-      fi
    done <<< "$aliases"
-   if [ $desc -eq 0 ]; then
+   
+   if [ $desc -eq 0 ] && [ $cr -eq 0 ]; then
       echo
    fi
    echo
+}
+
+function ___print_alias ()
+{
+   local desc=$1
+   local indent=$2
+   local cmd=$3
+   local value=
+   local suf=
+   local varname=
+   local c1=
+   local c2=
+
+   value=${BASH_ALIASES[$cmd]}
+   if [[ $value == *"sudo "* ]]; then
+      suf="*"
+      c1="\e[93m"
+      c2="\e[0m"
+   else
+      suf=""
+      c1=
+      c2=
+   fi
+   
+   if [ $desc -gt 0 ]; then
+      printf "   "
+      echo -e -n $c1
+      if [ $indent -gt 0 ]; then
+         printf %-16s $cmd$suf
+      else
+         printf %s $cmd$suf
+      fi
+      echo -e -n $c2
+
+      varname=${cmd//\./_}"_description"
+      if [[ -v $varname ]]; then
+         description=${!varname}
+      else
+         varname="_"$varname
+         if [[ -v $varname ]]; then
+            description=${!varname}
+         else
+            description="?"
+         fi
+      fi
+      echo " - $description"
+   else
+      echo -e -n $c1
+      printf %-16s $cmd$suf
+      echo -e -n $c2
+   fi
 }
